config/routes.rb
Scheduler::Application.routes.draw do
  root :to => 'static_pages#home'
	match 'login' => 'sessions#new'
	match 'logout' =>'sessions#destroy'
	match 'signup' => 'accounts#new'
	resource :dashboard,					:only => [:show]
	resources :password_resets,		:except => [:show, :destroy]
	
	resources :accounts do
		resources :addresses, 			:except => [:index, :show]
		resources :phones, 					:except => [:index, :show]
	end
  resources :sessions
	resources :passwords,					:only => [:new, :create]
  
  resources :employees do
  	member do
  		get 'activate'
  		get 'inactivate'
  	end
		resource :employment, 			:only => [:show, :edit, :update]
		resource :biography, 				:only => [:show, :edit, :update]
  end
	resources :people, 						:only => [] do
		resources :addresses, 			:except => [:index, :show]
		resources :phones, 					:except => [:index, :show]
		resources :users, 					:only => [:new, :create]
	end
	resources :users, 						:only => [:index, :edit, :update, :destroy]
	match 'users/:id/permissions', 	to: 'users#edit', :via => :get, :as => :edit_permissions
  
  resources :locations, 				:except => [:show] do
  	member do
  		get 'activate'
  		get 'inactivate'
  	end
  end
  
  resources :seasons
  resources :pieces do
		resources :scenes, :characters, :only => [:index, :new, :create]
  end
  resources :scenes, :characters, 	:only => [:edit, :update, :destroy] do
		collection { post :sort }
  end
  resources :season_pieces, 	:only => [] do
		resources :casts,					:only => [:index, :show, :new]
  end
  resources :casts,						:only => [:destroy]
	resources :castings,				:only => [:edit, :update]
	
	match 'features' => 'static_pages#features'
	match 'pricing' => 'static_pages#pricing'
	match 'contact' => 'static_pages#contact'
	
	resource :subscriptions, 					:only => [:show, :edit, :update, :destroy]
	resource :payments, 							:only => [:edit, :update]
	
	namespace :company do
		namespace :contract do	
			resource :rehearsal_week, 		:only => [:show, :edit, :update]
			resources :rehearsal_breaks, 	:only => [:new, :create, :destroy]
			resource :company_class, 			:only => [:show, :edit, :update]
			resource :costume_fitting, 		:only => [:show, :edit, :update]
			resource :lecture_demo, 			:only => [:show, :edit, :update]
		end
		resources :publish_casts,				:only => [:update]
	end
	
	namespace :schedule do
		resources :company_classes do
			get :dates, :on => :member
		end
		resources :rehearsals do
			post :scenes_by_piece, :on => :collection
		end
		resources :costume_fittings
		resources :lecture_demos
	  resources :events,						:except => [:new, :create] do
			resources :invitees, 				:only => [:index, :new, :create], :path_names => { :new => 'change' }
		end
	  match 'events/:year/:month/:day', to: 'events#index', :via => :get
		resources :selected_events,		:only => [:create]
	end
	
	namespace :current do
		resources :season,							:only => [:new, :create]
	end
	
	namespace :reports do
		resource :warning, 							:only => [:show]
	end
	
	namespace :admin do
		resources :accounts,						:only => [:index, :edit, :update, :destroy]
		resources :subscription_plans,	:except => [:show]
		resources :dropdowns,						:except => [:show] do
			collection { post :sort }
		end
	end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
	authorize_resource :class => false
	before_filter :get_resource, :only => [:show, :edit, :update, :destroy]

	def show
		@invoices = @account.list_invoices
		@next_invoice_date = @account.next_invoice_date
		show_stripe_errors
	end
	
	def edit
		form_setup
	end
	
	def update
		@account.current_subscription_plan_id = params[:account][:current_subscription_plan_id]
		
		if @account.edit_subscription_plan
			redirect_to subscriptions_path, :notice => "Successfully updated your Subscription"
		else
			form_setup
			render 'edit'
		end
	end
	
	def destroy
		if @account.cancel_subscription
  		redirect_to account_path(@account), :notice => "Your subscription has been canceled."
  	else
	  	show_stripe_errors
	  	redirect_to subscriptions_path
	  end
	end
	
private
	def get_resource
		@account = Account.find(Account.current_id)
	end
	
	#setup for form - dropdowns, etc
	def form_setup
		@plans = SubscriptionPlan.all.map { |plan| [plan.name_and_amount, plan.id] }
	end
	
	def show_stripe_errors
		if ! @account.errors.messages[:base].nil?
			@account.errors.messages[:base].each do |msg|
				flash[:error] = msg
			end
		end
	end
end

app/views/subscriptions/_detail.html.erb
<div class="dtl-form">
	<div class="row">
		<div class="dtl-label col-md-4"><%= Account.human_attribute_name(:current_subscription_plan) %></div>
		<div class="dtl-text col-md-8">
      <% if can? :update, :subscription %>
    		<%= link_to @account.current_subscription_plan.name , edit_subscriptions_path %>
      <% else %>
        <%= @account.current_subscription_plan.name %>
    	<% end %>
    </div>
	</div>
	
	<div class="row">
		<div class="dtl-label col-md-4">Next Payment On</div>
		<div class="dtl-text col-md-8"><%= @next_invoice_date.strftime('%B %-d, %Y') if @next_invoice_date %></div>
	</div>
</div>

app/views/subscriptions/_form.html.erb
<%= f.input :current_subscription_plan_id, 
      collection: @plans %>

app/views/subscriptions/_payment_history_table.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Payment History</h3>
  </div>
<% if @invoices && @invoices.length > 0 %>
  <table class="table table-striped">
  	<tbody>
  		<% @invoices.each do |invoice| %>
  		  <tr>
  		  	<td><%= Time.zone.at(invoice.date).to_date %></td>
  		  	<td><span class="text-right"><%= number_to_currency(invoice.total/100) %></span></td>
  		  	<td>Printable Receipt (PDF)</td>
  		  </tr>
  		<% end %>
  	</tbody>
  </table>
<% else %>
	<div class="panel-body">
    <p>No payments found.</p>
  </div>
<% end %>
</div>

app/views/subscriptions/edit.html.erb
<% provide(:title, 'My Account | Change Subscription') %>
<% provide(:header_current, 'Home') %>
<% provide(:sidebar_current, 'Account') %>

<div class="page-header">
  <h1>My Account
    <small>Change Subscription</small>
  </h1>
</div>

<div class="row mash-show">
	<%= render 'accounts/tabs' %>
	
	<div class="mash-body">
    <p class="text-muted">Fill out the form below to change your subscription. 
    	The new subscription will be charged to your current credit card.
    </p>

  	<%= simple_form_for @account, :url => subscriptions_path do |f| %>
  		<%= show_error_messages @account %>
  		<%= render 'form', :f => f %>
	
      <%= form_actions do %>
        <%= f.submit 'Update Subscription', class: 'btn btn-primary' %>
        <%= link_to 'Cancel', subscriptions_path, class: 'btn btn-link' if can? :read, :subscription %>
  		<% end %>
  	<% end %>

    <% if can? :destroy, :subscription %>
    	<h2>Cancel Your Subscription</h2>
    	<%= link_to 'Cancel Subscription', subscriptions_path, method: :delete, class:'col-md-offset-3 btn btn-danger' %>
    <% end %>
  </div>
</div>

app/views/subscriptions/show.html.erb
<% provide(:title, 'My Account | Subscription') %>
<% provide(:header_current, 'Home') %>
<% provide(:sidebar_current, 'Account') %>

<div class="page-header">
  <h1>My Account
    <small>Subscription</small>
    <div class="pull-right">
      <%= icon_link 'Change Payment Method', 'credit-card', edit_payments_path, class: 'btn btn-default' if can? :update, :payment %>
    </div>
  </h1>
</div>

<div class="row mash-show">
	<%= render 'accounts/tabs' %>
	
	<div class="mash-body">
    <%= render 'subscriptions/detail' %>
    
    <div class="row" style="margin-top:15px;">
      <div class="col-md-offset-1 col-md-10">
    		<%= render 'subscriptions/payment_history_table' %>
      </div>
    </div>
  </div>
</div>