config/routes.rb
Scheduler::Application.routes.draw do
  root :to => 'static_pages#home'
	match 'login' => 'sessions#new'
	match 'logout' =>'sessions#destroy'
	match 'signup' => 'accounts#new'
	resource :dashboard,					:only => [:show]
	resources :password_resets,		:except => [:show, :destroy]
	
	resources :accounts do
		resources :addresses, 			:except => [:index, :show]
		resources :phones, 					:except => [:index, :show]
	end
  resources :sessions
	resources :passwords,					:only => [:new, :create]
  
  resources :employees do
  	member do
  		get 'activate'
  		get 'inactivate'
  	end
		resource :employment, 			:only => [:show, :edit, :update]
		resource :biography, 				:only => [:show, :edit, :update]
  end
	resources :people, 						:only => [] do
		resources :addresses, 			:except => [:index, :show]
		resources :phones, 					:except => [:index, :show]
		resources :users, 					:only => [:new, :create]
	end
	resources :users, 						:only => [:index, :edit, :update, :destroy]
	match 'users/:id/permissions', 	to: 'users#edit', :via => :get, :as => :edit_permissions
  
  resources :locations, 				:except => [:show] do
  	member do
  		get 'activate'
  		get 'inactivate'
  	end
  end
  
  resources :seasons
  resources :pieces do
		resources :scenes, :characters, :only => [:index, :new, :create]
  end
  resources :scenes, :characters, 	:only => [:edit, :update, :destroy] do
		collection { post :sort }
  end
  resources :season_pieces, 	:only => [] do
		resources :casts,					:only => [:index, :show, :new]
  end
  resources :casts,						:only => [:destroy]
	resources :castings,				:only => [:edit, :update]
	
	match 'features' => 'static_pages#features'
	match 'pricing' => 'static_pages#pricing'
	match 'contact' => 'static_pages#contact'
	
	resource :subscriptions, 					:only => [:show, :edit, :update, :destroy]
	resource :payments, 							:only => [:edit, :update]
	
	namespace :company do
		namespace :contract do	
			resource :rehearsal_week, 		:only => [:show, :edit, :update]
			resources :rehearsal_breaks, 	:only => [:new, :create, :destroy]
			resource :company_class, 			:only => [:show, :edit, :update]
			resource :costume_fitting, 		:only => [:show, :edit, :update]
			resource :lecture_demo, 			:only => [:show, :edit, :update]
		end
		resources :publish_casts,				:only => [:update]
	end
	
	namespace :schedule do
		resources :company_classes do
			get :dates, :on => :member
		end
		resources :rehearsals do
			post :scenes_by_piece, :on => :collection
		end
		resources :costume_fittings
		resources :lecture_demos
	  resources :events,						:except => [:new, :create] do
			resources :invitees, 				:only => [:index, :new, :create], :path_names => { :new => 'change' }
		end
	  match 'events/:year/:month/:day', to: 'events#index', :via => :get
		resources :selected_events,		:only => [:create]
	end
	
	namespace :current do
		resources :season,							:only => [:new, :create]
	end
	
	namespace :reports do
		resource :warning, 							:only => [:show]
	end
	
	namespace :admin do
		resources :accounts,						:only => [:index, :edit, :update, :destroy]
		resources :subscription_plans,	:except => [:show]
		resources :dropdowns,						:except => [:show] do
			collection { post :sort }
		end
	end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
	authorize_resource :class => false
	
	def show
	end
end

app/controllers/schedule/company_classes_controller.rb
class Schedule::CompanyClassesController < ApplicationController
	load_resource :except => [:new, :create]
	authorize_resource
	layout 'tabs', :only => [:show, :dates]

	def index
		query = params.except(:action, :controller)
		@company_classes = @company_classes.search(query).order("company_classes.start_at DESC").paginate(page: params[:page], per_page: params[:per_page])
	end

	def new
		@company_class = CompanyClass.new(season_id: current_season.id)
		@company_class_form = CompanyClassForm.new(@company_class)
	end
	
	def create
		@company_class = CompanyClass.new(season_id: current_season.id)
		@company_class_form = CompanyClassForm.new(@company_class)
		if @company_class_form.submit(params[:company_class])
			redirect_to dates_schedule_company_class_path(@company_class_form.company_class), :notice => "Successfully created the company class."
		else
			render 'new'
		end
	end
	
	def edit
	end
	
	def update
		if @company_class.update_attributes(params[:company_class])
			redirect_to schedule_company_classes_path, :notice => "Successfully updated the company class."
		else
			render 'edit'
		end
	end
	
	def show
	end
	
	def destroy
		@company_class.destroy
		redirect_to schedule_company_classes_path, :notice => "Successfully deleted the company class."
	end
	
	def dates
		@events = @company_class.events
	end
end

app/controllers/schedule/costume_fittings_controller.rb
class Schedule::CostumeFittingsController < ApplicationController
	load_resource :except => [:new, :create]
	authorize_resource
	layout 'tabs', :except => [:index, :new, :create, :destroy]

	def index
		query = params.except(:action, :controller)
		@costume_fittings = @costume_fittings.joins(:event).search(query).order("events.start_at DESC").paginate(page: params[:page], per_page: params[:per_page])
	end

	def new
		@costume_fitting = CostumeFitting.new(season_id: current_season.id)
		@costume_fitting_form = CostumeFittingForm.new(@costume_fitting)
	end

  def create
		@costume_fitting = CostumeFitting.new(season_id: current_season.id)
		@costume_fitting_form = CostumeFittingForm.new(@costume_fitting)
		if @costume_fitting_form.submit(params[:costume_fitting])
			redirect_to schedule_costume_fittings_path, :notice => "Successfully created the costume fitting."
		else
			render 'new'
		end
	end
	
	def edit
		@costume_fitting_form = CostumeFittingForm.new(@costume_fitting)
	end
	
	def update
		@costume_fitting_form = CostumeFittingForm.new(@costume_fitting)
		if @costume_fitting_form.submit(params[:costume_fitting])
			redirect_to schedule_costume_fitting_path(@costume_fitting), :notice => "Successfully updated the costume fitting."
		else
			render 'edit'
		end
	end
	
	def show
	end
	
	def destroy
		@costume_fitting.destroy
		redirect_to schedule_costume_fittings_path, :notice => "Successfully deleted the costume fitting."
	end
end

app/controllers/schedule/events_controller.rb
class Schedule::EventsController < ApplicationController
	load_and_authorize_resource
	layout 'tabs', :only => [:show]

	def index
		params[:year] ||= Time.zone.today.year
		params[:month] ||= Time.zone.today.month
		params[:day] ||= Time.zone.today.day
		@event_date = Date.new(params[:year].to_i, params[:month].to_i, params[:day].to_i)
    
		if params[:range] == 'week'
			@date_range = @event_date.beginning_of_week..@event_date.end_of_week
	    @previous_day = @event_date - 1.week
	    @next_day = @event_date + 1.week
		else
			@date_range = @event_date..@event_date
	    @previous_day = @event_date - 1.day
	    @next_day = @event_date + 1.day
		end
		
		query = params.except(:action, :controller, :year, :month, :day)
		query[:date] = @event_date
		@events = @events.search(query)
		@events_by_date = @events.group_by { |e| e.start_at.to_date }
	end
	
	def show
	end
	
	def destroy
		@event.destroy
		redirect_to schedule_events_path+@event.start_at.strftime('/%Y/%-m/%-d'), :notice => "Successfully deleted the event."
	end
end

app/controllers/schedule/invitees_controller.rb
class Schedule::InviteesController < ApplicationController
	load_and_authorize_resource :event
	authorize_resource :invitees, :class => false
	layout 'tabs'
	
	def index
		@invitees = @event.invitees
		@artists = @event.artists
		@instructors = @event.instructors
		@musicians = @event.musicians
	end
	
	def new
	end
	
	def create
		if @event.update_attributes(params[:event])
			redirect_to schedule_event_invitees_path(@event), :notice => "Successfully updated the invitees."
		else
			render 'edit'
		end
	end
end

app/controllers/schedule/lecture_demos_controller.rb
class Schedule::LectureDemosController < ApplicationController
	load_resource :except => [:new, :create]
	authorize_resource
	layout 'tabs', :except => [:index, :new, :create, :destroy]

	def index
		query = params.except(:action, :controller)
		@lecture_demos = @lecture_demos.joins(:event).search(query).order("events.start_at DESC").paginate(page: params[:page], per_page: params[:per_page])
	end

	def new
		@lecture_demo = LectureDemo.new(season_id: current_season.id)
		@lecture_demo_form = LectureDemoForm.new(@lecture_demo)
	end

  def create
		@lecture_demo = LectureDemo.new(season_id: current_season.id)
		@lecture_demo_form = LectureDemoForm.new(@lecture_demo)
		if @lecture_demo_form.submit(params[:lecture_demo])
			redirect_to new_schedule_event_invitee_path(@lecture_demo_form.event), :notice => "Successfully created the lecture demonstration."
		else
			render 'new'
		end
	end
	
	def edit
		@lecture_demo_form = LectureDemoForm.new(@lecture_demo)
	end
	
	def update
		@lecture_demo_form = LectureDemoForm.new(@lecture_demo)
		if @lecture_demo_form.submit(params[:lecture_demo])
			redirect_to schedule_lecture_demos_path, :notice => "Successfully updated the lecture demonstration."
		else
			render 'edit'
		end
	end
	
	def show
	end
	
	def destroy
		@lecture_demo.destroy
		redirect_to schedule_lecture_demos_path, :notice => "Successfully deleted the lecture demonstration."
	end
end

app/controllers/schedule/rehearsals_controller.rb
class Schedule::RehearsalsController < ApplicationController
	load_resource :except => [:new, :create]
	authorize_resource
	layout 'tabs', :except => [:index, :new, :create, :destroy]

	def index
		query = params.except(:action, :controller)
		@rehearsals = @rehearsals.joins(:event).search(query).order("events.start_at DESC").paginate(page: params[:page], per_page: params[:per_page])
	end

	def new
		@rehearsal = Rehearsal.new(season_id: current_season.id)
		@rehearsal_form = RehearsalForm.new(@rehearsal)
	end

  def create
		@rehearsal = Rehearsal.new(season_id: current_season.id)
		@rehearsal_form = RehearsalForm.new(@rehearsal)
		if @rehearsal_form.submit(params[:rehearsal])
			redirect_to new_schedule_event_invitee_path(@rehearsal_form.event), :notice => "Successfully created the rehearsal."
		else
			render 'new'
		end
	end
	
	def edit
		@rehearsal_form = RehearsalForm.new(@rehearsal)
	end
	
	def update
		@rehearsal_form = RehearsalForm.new(@rehearsal)
		if @rehearsal_form.submit(params[:rehearsal])
			redirect_to schedule_rehearsals_path, :notice => "Successfully updated the rehearsal."
		else
			render 'edit'
		end
	end
	
	def show
	end
	
	def destroy
		@rehearsal.destroy
		redirect_to schedule_rehearsals_path, :notice => "Successfully deleted the rehearsal."
	end
	
	def scenes_by_piece
		@scenes = params[:piece_id].present? ? Piece.find(params[:piece_id]).scenes : []

		respond_to do |format|
			format.js
		end
	end
end

app/controllers/schedule/selected_events_controller.rb
class Schedule::SelectedEventsController < ApplicationController
	authorize_resource :selected_events, :class => false

	def create
		if params[:event_ids].present?
			@events = Event.find(params[:event_ids])
			@event = @events.first
			
			if params[:commit] == 'Update'
				@events.reject! do |event|
					event.update_attributes(params[:event].reject { |k,v| v.blank? })
				end
				redirect_to dates_schedule_company_class_path(@event.schedulable), :notice => "Successfully updated the selected events." if @events.empty?
			else
				render 'new'
			end
		else
			redirect_to :back
		end
	end
end

app/helpers/schedule_helper.rb
module ScheduleHelper
	def min_to_words(total_min)
		hrs = total_min / 60
		min = total_min % 60
		out = (hrs == 0) ? "" : pluralize(hrs, "hour")+ " "
		out += (min == 0) ? "" : pluralize(min, "minute")
		
		out.strip
	end
	
	def name_or_tbd(resource)
		resource ? resource.name : 'TBD'
	end
end

app/views/schedule/calendar/_new_modal.html.erb
<div class="modal fade" id="newModal" tabindex="-1" role="dialog" aria-labelledby="newModalLabel" aria-hidden="true">
<div class="modal-dialog">
<div class="modal-content">

	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h3 class="modal-title" id="newModalLabel">
			<%= content_tag(:span, nil, class: "glyphicon glyphicon-plus mash-green") %> Select an Event Type
		</h3>
	</div>

	<%= form_tag new_schedule_event_path, class:"form-horizontal", method:"get" do |f| %>
		<div class="modal-body">
			<div class="form-group">
				<div class="col-md-offset-2 col-md-10">
					<% if can? :create, CompanyClass %>
						<div class="radio">
				  		<label>
				  			<%= radio_button_tag 'event_type', 'CompanyClass' %>
				    		Company Class
				  		</label>
						</div>
					<% end %>
					<% if can? :create, Rehearsal %>
						<div class="radio">
				  		<label>
				    		<%= radio_button_tag 'event_type', 'Rehearsal' %>
				    		Rehearsal
				  		</label>
						</div>
					<% end %>
					<% if can? :create, CostumeFitting %>
						<div class="radio">
				  		<label>
				    		<%= radio_button_tag 'event_type', 'CostumeFitting' %>
				    		Costume Fitting
				  		</label>
						</div>
					<% end %>
					<% if can? :create, Event %>
						<div class="radio">
				  		<label>
				    		<%= radio_button_tag 'event_type', 'Event' %>
				    		Event
				  		</label>
						</div>
					<% end %>
		    </div>
  	</div>
  	<%= hidden_field_tag 'dt' %>
		<%= hidden_field_tag 'tm' %>
  </div><!-- modal-body -->

	<div class="modal-footer">
		<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
		<%= submit_tag 'Next', name: nil, class: "btn btn-success" %>
	</div>
<% end %>
	
</div> <!-- modal-content -->
</div> <!-- modal-dialog -->
</div> <!-- modal -->

app/views/schedule/calendar/_tools_menu.html.erb
<div class="pull-right">
  <%= gear_dropdown do %>
		<% if can? :create, CompanyClass %>
			<li><%= new_link "Add Company Class", new_schedule_company_class_path(date: @date) %></li>
		<% end %>
    
		<% if can? :create, Rehearsal %>
			<li><%= new_link "Add Rehearsal", new_schedule_rehearsal_path(date: @date) %></li>
		<% end %>
		
		<% if can? :create, CostumeFitting %>
			<li><%= new_link "Add Costume Fitting", new_schedule_costume_fitting_path(date: @date) %></li>
		<% end %>
    
		<% if can? :create, LectureDemo %>
			<li><%= new_link "Add Lecture Demo", new_schedule_lecture_demo_path(date: @date) %></li>
		<% end %>
		
		<% if can? :create, Event %>
			<li><%= new_link "Add Event", new_schedule_event_path(date: @date) %></li>
		<% end %>
  <% end %>
</div>

app/views/schedule/calendar/index.html.erb
<% provide(:title, 'Events') %>
<% provide(:header_current, 'Calendar') %>
<% provide(:sidebar_current, 'Events') %>

<div class="page-header">
	 <h1><%= yield(:title) %>
   </h1>
</div>

<%= render 'events/search_form' %>

<div class="row">
  	<table class="table table-striped">
  		<thead>
  	  	<tr>
  	  		<th>Name</th>
  	  		<th>Status</th>
  	  		<th class="mash-col-2-btn">&nbsp;</th>
  	  	</tr>
  	  </thead>
  	  <tbody>
  	  	<% @events.each do |event| %>
  				<tr>
  					<td>
  						<% if can? :update, location %>
  							<%= link_to location.name, edit_location_path(location), :id => "edit_#{location.id}" %>
              <% else %>
                <%= location.name %>
  						<% end %>
            </td>
  					<td><%= location.status %></td>
  					<td class="mash-col-2-btn">
  						<%= activate_button nil, activate_location_path(location), :class => 'btn-xs', :id => "activate_#{location.id}" if !location.active && can?(:activate, location) %>
  						<%= inactivate_button nil, inactivate_location_path(location), :class => 'btn-xs', :id => "inactivate_#{location.id}" if location.active && can?(:inactivate, location) %>
  						<%= delete_button nil, location, :class => 'btn-xs', :id => "delete_#{location.id}" if can? :destroy, location %>
  					</td>
  				</tr>
  			<% end %>
  		</tbody>
  	</table>

  <% else %>
  	<p>Some businesses have multiple locations that operate as a single entity - with a single 
  		list of staff and students.  If you have more than one location, each physical address 
  		can be entered as a separate location. Each location can then maintain a set of rooms used 
  		for rehearsals, performaces, or classes with a seperate schedule.
  	</p>
  	<p>To begin, click the <em class="text-info">Add Location</em> link above.</p>
  <% end %>
</div>