config/routes.rb
Scheduler::Application.routes.draw do
  root :to => 'static_pages#home'
	match 'login' => 'sessions#new'
	match 'logout' =>'sessions#destroy'
	match 'signup' => 'accounts#new'
	resource :dashboard,					:only => [:show]
	resources :password_resets,		:except => [:show, :destroy]
	
	resources :accounts do
		resources :addresses, 			:except => [:index, :show]
		resources :phones, 					:except => [:index, :show]
	end
  resources :sessions
	resources :passwords,					:only => [:new, :create]
  
  resources :employees do
  	member do
  		get 'activate'
  		get 'inactivate'
  	end
		resource :employment, 			:only => [:show, :edit, :update]
		resource :biography, 				:only => [:show, :edit, :update]
  end
	resources :people, 						:only => [] do
		resources :addresses, 			:except => [:index, :show]
		resources :phones, 					:except => [:index, :show]
		resources :users, 					:only => [:new, :create]
	end
	resources :users, 						:only => [:index, :edit, :update, :destroy]
	match 'users/:id/permissions', 	to: 'users#edit', :via => :get, :as => :edit_permissions
  
  resources :locations, 				:except => [:show] do
  	member do
  		get 'activate'
  		get 'inactivate'
  	end
  end
  
  resources :seasons
  resources :pieces do
		resources :scenes, :characters, :only => [:index, :new, :create]
  end
  resources :scenes, :characters, 	:only => [:edit, :update, :destroy] do
		collection { post :sort }
  end
  resources :season_pieces, 	:only => [] do
		resources :casts,					:only => [:index, :show, :new]
  end
  resources :casts,						:only => [:destroy]
	resources :castings,				:only => [:edit, :update]
	
	match 'features' => 'static_pages#features'
	match 'pricing' => 'static_pages#pricing'
	match 'contact' => 'static_pages#contact'
	
	resource :subscriptions, 					:only => [:show, :edit, :update, :destroy]
	resource :payments, 							:only => [:edit, :update]
	
	namespace :company do
		namespace :contract do	
			resource :rehearsal_week, 		:only => [:show, :edit, :update]
			resources :rehearsal_breaks, 	:only => [:new, :create, :destroy]
			resource :company_class, 			:only => [:show, :edit, :update]
			resource :costume_fitting, 		:only => [:show, :edit, :update]
			resource :lecture_demo, 			:only => [:show, :edit, :update]
		end
		resources :publish_casts,				:only => [:update]
	end
	
	namespace :schedule do
		resources :company_classes do
			get :dates, :on => :member
		end
		resources :rehearsals do
			post :scenes_by_piece, :on => :collection
		end
		resources :costume_fittings
		resources :lecture_demos
	  resources :events,						:except => [:new, :create] do
			resources :invitees, 				:only => [:index, :new, :create], :path_names => { :new => 'change' }
		end
	  match 'events/:year/:month/:day', to: 'events#index', :via => :get
		resources :selected_events,		:only => [:create]
	end
	
	namespace :current do
		resources :season,							:only => [:new, :create]
	end
	
	namespace :reports do
		resource :warning, 							:only => [:show]
	end
	
	namespace :admin do
		resources :accounts,						:only => [:index, :edit, :update, :destroy]
		resources :subscription_plans,	:except => [:show]
		resources :dropdowns,						:except => [:show] do
			collection { post :sort }
		end
	end
end

app/views/layouts/sidebars/_administration.html.erb
<% klass = ' class="active"'.html_safe %>
<nav class="navbar navbar-default mash-sub-navbar" role="navigation">
  <ul class="nav navbar-nav">
		<% if can? :read, Account && current_user.superadmin? %>
			<li<%= klass if yield(:sidebar_current) == "Accounts" %>>
        <%= link_to "Accounts", admin_accounts_path %>
      </li>
		<% end %>
    
		<% if can? :read, SubscriptionPlan && current_user.superadmin? %>
			<li<%= klass if yield(:sidebar_current) == "Subscription Plans" %>>
        <%= link_to "Subscription Plans", admin_subscription_plans_path %>
      </li>
		<% end %>
    
		<% if can? :read, Dropdown && current_user.superadmin? %>
			<li<%= klass if yield(:sidebar_current) == "Dropdowns" %>>
        <%= link_to "Dropdowns", admin_dropdowns_path %>
      </li>
		<% end %>
  </ul>
</nav>

app/views/layouts/sidebars/_calendar.html.erb
<% klass = ' class="active"'.html_safe %>
<nav class="navbar navbar-default mash-sub-navbar" role="navigation">
  <ul class="nav navbar-nav">
		<% if can? :read, Event %>
			<li<%= klass if yield(:sidebar_current) == "Events" %>>
				<%= link_to "Events", schedule_events_path %>
			</li>
		<% end %>
    
    <% if can? :read, CompanyClass %>
		  <li<%= klass if yield(:sidebar_current) == "Company Classes" %>>
        <%= link_to "Company Classes", schedule_company_classes_path %>
      </li>
		<% end %>
    
		<% if can? :read, Rehearsal %>
			<li<%= klass if yield(:sidebar_current) == "Rehearsals" %>>
        <%= link_to "Rehearsals", schedule_rehearsals_path %>
      </li>
		<% end %>
		
		<% if can? :read, CostumeFitting %>
			<li<%= klass if yield(:sidebar_current) == "Costume Fittings" %>>
        <%= link_to "Costume Fittings", schedule_costume_fittings_path %>
      </li>
		<% end %>
    
		<% if can? :read, LectureDemo %>
			<li<%= klass if yield(:sidebar_current) == "Lecture Demos" %>>
        <%= link_to "Lecture Demos", schedule_lecture_demos_path %>
      </li>
		<% end %>
  </ul>
</nav>

app/views/layouts/sidebars/_home.html.erb
<% klass = ' class="active"'.html_safe %>
<nav class="navbar navbar-default mash-sub-navbar" role="navigation">
  <ul class="nav navbar-nav">
    <% if can? :read, :dashboard %>
      <li<%= klass if yield(:sidebar_current) == "Dashboard" %>>
        <%= icon_link 'Dashboard', 'dashboard', dashboard_path %>
      </li>
    <% end %>
    
		<% if can? :show, current_user.account %>
			<li<%= klass if yield(:sidebar_current) == "Account" %>>
				<%= link_to "My Account", account_path(current_user.account_id) %>
			</li>
		<% end %>
  </ul>
</nav>

app/views/layouts/sidebars/_people.html.erb
<% klass = ' class="active"'.html_safe %>
<nav class="navbar navbar-default mash-sub-navbar" role="navigation">
  <ul class="nav navbar-nav">
		<% if can? :index, Employee %>
			<li<%= klass if yield(:sidebar_current) == "Employees" %>>
				<%= link_to "Employees", employees_path %>
			</li>
		<% end %>
		
		<% if can? :read, User %>
			<li<%= klass if yield(:sidebar_current) == "Users" %>>
				<%= link_to "Users", users_path %>
			</li>
		<% end %>
  </ul>
</nav>

app/views/layouts/sidebars/_reports.html.erb
<% klass = ' class="active"'.html_safe %>
<nav class="navbar navbar-default mash-sub-navbar" role="navigation">
  <ul class="nav navbar-nav">
		<% if can? :read, :warnings_report %>
			<li<%= klass if yield(:sidebar_current) == "Warnings" %>>
				<%= link_to "Warnings", reports_warning_path %>
			</li>
		<% end %>
  </ul>
</nav>

app/views/layouts/sidebars/_setup.html.erb
<% klass = ' class="active"'.html_safe %>
<nav class="navbar navbar-default mash-sub-navbar" role="navigation">
  <ul class="nav navbar-nav">
		<% if can? :read, Location %>
			<li<%= klass if yield(:sidebar_current) == "Locations" %>>
				<%= link_to "Locations", locations_path(status: "active") %>
			</li>
		<% end %>
    
		<% if can? :read, :contract_rehearsal_week %>
			<li<%= klass if yield(:sidebar_current) == "Contract" %>>
				<%= link_to "Contract Settings", company_contract_rehearsal_week_path %>
			</li>
		<% end %>
				
		<% if can? :read, Season %>
			<li<%= klass if yield(:sidebar_current) == "Seasons" %>>
				<%= link_to "Seasons", seasons_path %>
			</li>
		<% end %>
		
		<% if can? :read, Piece %>
			<li<%= klass if yield(:sidebar_current) == "Pieces" %>>
				<%= link_to "Pieces", pieces_path %>
			</li>
		<% end %>
  </ul>
</nav>