config/routes.rb
Scheduler::Application.routes.draw do
  root :to => 'static_pages#home'
	match 'login' => 'sessions#new'
	match 'logout' =>'sessions#destroy'
	match 'signup' => 'accounts#new'
	resource :dashboard,					:only => [:show]
	resources :password_resets,		:except => [:show, :destroy]
	
	resources :accounts do
		resources :addresses, 			:except => [:index, :show]
		resources :phones, 					:except => [:index, :show]
	end
  resources :sessions
	resources :passwords,					:only => [:new, :create]
  
  resources :employees do
  	member do
  		get 'activate'
  		get 'inactivate'
  	end
		resource :employment, 			:only => [:show, :edit, :update]
		resource :biography, 				:only => [:show, :edit, :update]
  end
	resources :people, 						:only => [] do
		resources :addresses, 			:except => [:index, :show]
		resources :phones, 					:except => [:index, :show]
		resources :users, 					:only => [:new, :create]
	end
	resources :users, 						:only => [:index, :edit, :update, :destroy]
	match 'users/:id/permissions', 	to: 'users#edit', :via => :get, :as => :edit_permissions
  
  resources :locations, 				:except => [:show] do
  	member do
  		get 'activate'
  		get 'inactivate'
  	end
  end
  
  resources :seasons
  resources :pieces do
		resources :scenes, :characters, :only => [:index, :new, :create]
  end
  resources :scenes, :characters, 	:only => [:edit, :update, :destroy] do
		collection { post :sort }
  end
  resources :season_pieces, 	:only => [] do
		resources :casts,					:only => [:index, :show, :new]
  end
  resources :casts,						:only => [:destroy]
	resources :castings,				:only => [:edit, :update]
	
	match 'features' => 'static_pages#features'
	match 'pricing' => 'static_pages#pricing'
	match 'contact' => 'static_pages#contact'
	
	resource :subscriptions, 					:only => [:show, :edit, :update, :destroy]
	resource :payments, 							:only => [:edit, :update]
	
	namespace :company do
		namespace :contract do	
			resource :rehearsal_week, 		:only => [:show, :edit, :update]
			resources :rehearsal_breaks, 	:only => [:new, :create, :destroy]
			resource :company_class, 			:only => [:show, :edit, :update]
			resource :costume_fitting, 		:only => [:show, :edit, :update]
			resource :lecture_demo, 			:only => [:show, :edit, :update]
		end
		resources :publish_casts,				:only => [:update]
	end
	
	namespace :schedule do
		resources :company_classes do
			get :dates, :on => :member
		end
		resources :rehearsals do
			post :scenes_by_piece, :on => :collection
		end
		resources :costume_fittings
		resources :lecture_demos
	  resources :events,						:except => [:new, :create] do
			resources :invitees, 				:only => [:index, :new, :create], :path_names => { :new => 'change' }
		end
	  match 'events/:year/:month/:day', to: 'events#index', :via => :get
		resources :selected_events,		:only => [:create]
	end
	
	namespace :current do
		resources :season,							:only => [:new, :create]
	end
	
	namespace :reports do
		resource :warning, 							:only => [:show]
	end
	
	namespace :admin do
		resources :accounts,						:only => [:index, :edit, :update, :destroy]
		resources :subscription_plans,	:except => [:show]
		resources :dropdowns,						:except => [:show] do
			collection { post :sort }
		end
	end
end

app/models/costume_fitting.rb
# == Schema Information
#
# Table name: costume_fittings
#
#  id         :integer          not null, primary key
#  account_id :integer          not null
#  season_id  :integer          not null
#  title      :string(30)       not null
#  comment    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CostumeFitting < ActiveRecord::Base
	include ActionView::Helpers::TextHelper
	
  attr_accessible :title, :comment, :season_id

	belongs_to :account, 	inverse_of: :costume_fittings
	belongs_to :season, 	inverse_of: :costume_fittings
	has_one :event, :as => :schedulable, dependent: :destroy
	has_one :location, :through => :event
	has_many :invitations, :through => :event
	has_many :invitees, through: :invitations, source: :person
	
	delegate :start_date, :start_time, :duration, :time_range, to: :event
	
	validates :account,	presence: true
	validates :season,	presence: true
	validates :title, presence: true, length: { maximum: 30 }
	validate :check_contract_duration
	
	default_scope lambda { where(:account_id => Account.current_id) }
	
	def self.search(query)
		#Default show all
		costume_fittings = CostumeFitting.joins(:event)
		
		if query.include?(:title) && query[:title].present?
			costume_fittings = costume_fittings.where('costume_fittings.title LIKE :q', q: "%#{query[:title]}%")
		end
		
		if query.include?(:season) && query[:season].present?
			costume_fittings = costume_fittings.where(season_id: query[:season])
		end

		if query.include?(:loc) && query[:loc].present?
			costume_fittings = costume_fittings.where(events: { location_id: query[:loc] })
		end
		
		costume_fittings
	end
	
	def event
		super || build_event(title: title)
	end

private
	def check_contract_duration
		if duration.present? && contract && contract.costume_increment_min.present? 
			increment = contract.costume_increment_min
			if (duration % increment) != 0
				errors.add(:duration, "must be in increments of #{pluralize(increment, 'minute')}")
			end
		end
	end
	
	def contract
		@contract ||= AgmaContract.first
	end
end

app/controllers/company/contract/costume_fitting_controller.rb
class Company::Contract::CostumeFittingController < ApplicationController
	before_filter :get_resource
	layout 'tabs'
	
  def show
		authorize! :show, :contract_costume_fitting
  end
	
  def edit
		authorize! :edit, :contract_costume_fitting
  end
	
  def update
		authorize! :update, :contract_costume_fitting
		if @agma_contract.update_attributes(params[:agma_contract])
			redirect_to company_contract_costume_fitting_path, :notice => "Successfully updated the Costume Fitting Settings"
		else
			render 'edit'
		end
  end
	
private
	def get_resource
		@agma_contract = AgmaContract.first
	end
end

app/controllers/company/contract/costume_fittings_controller.rb
class Company::Contract::CostumeFittingsController < ApplicationController
	before_filter :get_resource
	layout 'tabs'
	
  def show
		authorize! :show, :contract_costume_fitting
  end
	
  def edit
		authorize! :edit, :contract_costume_fitting
  end
	
  def update
		authorize! :update, :contract_costume_fitting
		if @agma_contract.update_attributes(params[:agma_contract])
			redirect_to company_contract_costume_fitting_path, :notice => "Successfully updated the Costume Fitting Settings"
		else
			render 'edit'
		end
  end
	
private
	def get_resource
		@agma_contract = AgmaContract.first
	end
end

app/controllers/schedule/company_classes_controller.rb
class Schedule::CompanyClassesController < ApplicationController
	load_resource :except => [:new, :create]
	authorize_resource
	layout 'tabs', :only => [:show, :dates]

	def index
		query = params.except(:action, :controller)
		@company_classes = @company_classes.search(query).order("company_classes.start_at DESC").paginate(page: params[:page], per_page: params[:per_page])
	end

	def new
		@company_class = CompanyClass.new(season_id: current_season.id)
		@company_class_form = CompanyClassForm.new(@company_class)
	end
	
	def create
		@company_class = CompanyClass.new(season_id: current_season.id)
		@company_class_form = CompanyClassForm.new(@company_class)
		if @company_class_form.submit(params[:company_class])
			redirect_to dates_schedule_company_class_path(@company_class_form.company_class), :notice => "Successfully created the company class."
		else
			render 'new'
		end
	end
	
	def edit
	end
	
	def update
		if @company_class.update_attributes(params[:company_class])
			redirect_to schedule_company_classes_path, :notice => "Successfully updated the company class."
		else
			render 'edit'
		end
	end
	
	def show
	end
	
	def destroy
		@company_class.destroy
		redirect_to schedule_company_classes_path, :notice => "Successfully deleted the company class."
	end
	
	def dates
		@events = @company_class.events
	end
end

app/controllers/schedule/costume_fittings_controller.rb
class Schedule::CostumeFittingsController < ApplicationController
	load_resource :except => [:new, :create]
	authorize_resource
	layout 'tabs', :except => [:index, :new, :create, :destroy]

	def index
		query = params.except(:action, :controller)
		@costume_fittings = @costume_fittings.joins(:event).search(query).order("events.start_at DESC").paginate(page: params[:page], per_page: params[:per_page])
	end

	def new
		@costume_fitting = CostumeFitting.new(season_id: current_season.id)
		@costume_fitting_form = CostumeFittingForm.new(@costume_fitting)
	end

  def create
		@costume_fitting = CostumeFitting.new(season_id: current_season.id)
		@costume_fitting_form = CostumeFittingForm.new(@costume_fitting)
		if @costume_fitting_form.submit(params[:costume_fitting])
			redirect_to schedule_costume_fittings_path, :notice => "Successfully created the costume fitting."
		else
			render 'new'
		end
	end
	
	def edit
		@costume_fitting_form = CostumeFittingForm.new(@costume_fitting)
	end
	
	def update
		@costume_fitting_form = CostumeFittingForm.new(@costume_fitting)
		if @costume_fitting_form.submit(params[:costume_fitting])
			redirect_to schedule_costume_fitting_path(@costume_fitting), :notice => "Successfully updated the costume fitting."
		else
			render 'edit'
		end
	end
	
	def show
	end
	
	def destroy
		@costume_fitting.destroy
		redirect_to schedule_costume_fittings_path, :notice => "Successfully deleted the costume fitting."
	end
end

app/controllers/schedule/events_controller.rb
class Schedule::EventsController < ApplicationController
	load_and_authorize_resource
	layout 'tabs', :only => [:show]

	def index
		params[:year] ||= Time.zone.today.year
		params[:month] ||= Time.zone.today.month
		params[:day] ||= Time.zone.today.day
		@event_date = Date.new(params[:year].to_i, params[:month].to_i, params[:day].to_i)
    
		if params[:range] == 'week'
			@date_range = @event_date.beginning_of_week..@event_date.end_of_week
	    @previous_day = @event_date - 1.week
	    @next_day = @event_date + 1.week
		else
			@date_range = @event_date..@event_date
	    @previous_day = @event_date - 1.day
	    @next_day = @event_date + 1.day
		end
		
		query = params.except(:action, :controller, :year, :month, :day)
		query[:date] = @event_date
		@events = @events.search(query)
		@events_by_date = @events.group_by { |e| e.start_at.to_date }
	end
	
	def show
	end
	
	def destroy
		@event.destroy
		redirect_to schedule_events_path+@event.start_at.strftime('/%Y/%-m/%-d'), :notice => "Successfully deleted the event."
	end
end

app/controllers/schedule/invitees_controller.rb
class Schedule::InviteesController < ApplicationController
	load_and_authorize_resource :event
	authorize_resource :invitees, :class => false
	layout 'tabs'
	
	def index
		@invitees = @event.invitees
		@artists = @event.artists
		@instructors = @event.instructors
		@musicians = @event.musicians
	end
	
	def new
	end
	
	def create
		if @event.update_attributes(params[:event])
			redirect_to schedule_event_invitees_path(@event), :notice => "Successfully updated the invitees."
		else
			render 'edit'
		end
	end
end

app/controllers/schedule/lecture_demos_controller.rb
class Schedule::LectureDemosController < ApplicationController
	load_resource :except => [:new, :create]
	authorize_resource
	layout 'tabs', :except => [:index, :new, :create, :destroy]

	def index
		query = params.except(:action, :controller)
		@lecture_demos = @lecture_demos.joins(:event).search(query).order("events.start_at DESC").paginate(page: params[:page], per_page: params[:per_page])
	end

	def new
		@lecture_demo = LectureDemo.new(season_id: current_season.id)
		@lecture_demo_form = LectureDemoForm.new(@lecture_demo)
	end

  def create
		@lecture_demo = LectureDemo.new(season_id: current_season.id)
		@lecture_demo_form = LectureDemoForm.new(@lecture_demo)
		if @lecture_demo_form.submit(params[:lecture_demo])
			redirect_to new_schedule_event_invitee_path(@lecture_demo_form.event), :notice => "Successfully created the lecture demonstration."
		else
			render 'new'
		end
	end
	
	def edit
		@lecture_demo_form = LectureDemoForm.new(@lecture_demo)
	end
	
	def update
		@lecture_demo_form = LectureDemoForm.new(@lecture_demo)
		if @lecture_demo_form.submit(params[:lecture_demo])
			redirect_to schedule_lecture_demos_path, :notice => "Successfully updated the lecture demonstration."
		else
			render 'edit'
		end
	end
	
	def show
	end
	
	def destroy
		@lecture_demo.destroy
		redirect_to schedule_lecture_demos_path, :notice => "Successfully deleted the lecture demonstration."
	end
end

app/controllers/schedule/rehearsals_controller.rb
class Schedule::RehearsalsController < ApplicationController
	load_resource :except => [:new, :create]
	authorize_resource
	layout 'tabs', :except => [:index, :new, :create, :destroy]

	def index
		query = params.except(:action, :controller)
		@rehearsals = @rehearsals.joins(:event).search(query).order("events.start_at DESC").paginate(page: params[:page], per_page: params[:per_page])
	end

	def new
		@rehearsal = Rehearsal.new(season_id: current_season.id)
		@rehearsal_form = RehearsalForm.new(@rehearsal)
	end

  def create
		@rehearsal = Rehearsal.new(season_id: current_season.id)
		@rehearsal_form = RehearsalForm.new(@rehearsal)
		if @rehearsal_form.submit(params[:rehearsal])
			redirect_to new_schedule_event_invitee_path(@rehearsal_form.event), :notice => "Successfully created the rehearsal."
		else
			render 'new'
		end
	end
	
	def edit
		@rehearsal_form = RehearsalForm.new(@rehearsal)
	end
	
	def update
		@rehearsal_form = RehearsalForm.new(@rehearsal)
		if @rehearsal_form.submit(params[:rehearsal])
			redirect_to schedule_rehearsals_path, :notice => "Successfully updated the rehearsal."
		else
			render 'edit'
		end
	end
	
	def show
	end
	
	def destroy
		@rehearsal.destroy
		redirect_to schedule_rehearsals_path, :notice => "Successfully deleted the rehearsal."
	end
	
	def scenes_by_piece
		@scenes = params[:piece_id].present? ? Piece.find(params[:piece_id]).scenes : []

		respond_to do |format|
			format.js
		end
	end
end

app/controllers/schedule/selected_events_controller.rb
class Schedule::SelectedEventsController < ApplicationController
	authorize_resource :selected_events, :class => false

	def create
		if params[:event_ids].present?
			@events = Event.find(params[:event_ids])
			@event = @events.first
			
			if params[:commit] == 'Update'
				@events.reject! do |event|
					event.update_attributes(params[:event].reject { |k,v| v.blank? })
				end
				redirect_to dates_schedule_company_class_path(@event.schedulable), :notice => "Successfully updated the selected events." if @events.empty?
			else
				render 'new'
			end
		else
			redirect_to :back
		end
	end
end

app/helpers/schedule_helper.rb
module ScheduleHelper
	def min_to_words(total_min)
		hrs = total_min / 60
		min = total_min % 60
		out = (hrs == 0) ? "" : pluralize(hrs, "hour")+ " "
		out += (min == 0) ? "" : pluralize(min, "minute")
		
		out.strip
	end
	
	def name_or_tbd(resource)
		resource ? resource.name : 'TBD'
	end
end

app/views/schedule/costume_fittings/_detail.html.erb
<div class="dtl-form">
	<div class="row">
		<div class="dtl-label col-sm-2 col-md-2"><%= CostumeFitting.human_attribute_name(:title) %></div>
		<div class="dtl-text col-sm-4 col-md-4"><%= @costume_fitting.title %></div>
    
		<div class="dtl-label col-sm-2 col-md-2"><%= CostumeFitting.human_attribute_name(:location) %></div>
		<div class="dtl-text col-sm-4 col-md-4"><%= name_or_tbd(@costume_fitting.location) %></div>
	</div>
  
	<div class="row">
		<div class="dtl-label col-sm-2 col-md-2"><%= CostumeFitting.human_attribute_name(:comment) %></div>
		<div class="dtl-text col-sm-10 col-md-10"><%= simple_format(@costume_fitting.comment) %></div>
	</div>
  
	<div class="row">
		<div class="dtl-label col-sm-2 col-md-2"><%= CostumeFitting.human_attribute_name(:start_date) %></div>
		<div class="dtl-text col-sm-4 col-md-4"><%= @costume_fitting.start_date(:date_words) %></div>
	</div>
  
	<div class="row">
		<div class="dtl-label col-sm-2 col-md-2"><%= CostumeFitting.human_attribute_name(:start_time) %></div>
		<div class="dtl-text col-sm-4 col-md-4"><%= @costume_fitting.time_range %></div>
    
		<div class="dtl-label col-sm-2 col-md-2"><%= CompanyClass.human_attribute_name(:duration) %></div>
		<div class="dtl-text col-sm-4 col-md-4"><%= min_to_words(@costume_fitting.duration) %></div>
	</div>
</div>

app/views/schedule/costume_fittings/_form.html.erb
<%= f.input :title,
      required: true %>
<%= f.input :location_id, 
      collection: Location.active, 
      include_blank: true %>
<%= f.input :season_id, as: :static_control,
      text: @costume_fitting.season.name,
      required: true %>
<span id="season_start_date" class="hidden"><%= @costume_fitting.season.start_dt %></span>
<span id="season_end_date" class="hidden"><%= @costume_fitting.season.end_dt %></span>

<%= f.input :start_date, as: :date_picker,
      required: true  %>

<%= f.input :start_time, required: true do %>
  <div class="col-sm-4 col-md-4">
    <%= f.input_field :start_time, as: :time_prepend  %>
  </div>
  
  <%= f.label :duration, required: true  %>
  <div class="col-sm-3 col-md-3">
    <%= f.input_field :duration, as: :append,
        append_text:'min' %>
  </div>
<% end %>

<%= f.input :comment, as: :text,
      input_html: { rows: 5 } %>

app/views/schedule/costume_fittings/_search_form.html.erb
<div class="search-row hidden-print">
  <%= form_tag schedule_costume_fittings_path, method: 'get', class: 'form-inline', id: 'costume_fitting_search' do %>
		<div class="form-group">
      <%= label :title, 'Title', class: 'sr-only' %>
      <%= text_field_tag :title, 
            params[:title], 
            class: 'form-control',
            placeholder: 'Title' %>
    </div>
		<div class="form-group">
      <%= label :season, 'Season', class: 'sr-only' %>
      <%= select_tag :season,
          options_from_collection_for_select(Season.all, :id, :name, params[:season]),
          prompt: 'All Seasons',
          class: 'form-control submit-on-change'
        %>
    </div>
		<div class="form-group">
      <%= label :loc, 'Location', class: 'sr-only' %>
      <%= select_tag :loc,
          options_from_collection_for_select(Location.active.all, :id, :name, params[:loc]),
          prompt: 'All Locations',
          class: 'form-control submit-on-change'
        %>
    </div>
    <%= content_tag :button, content_tag(:span, nil, class: 'glyphicon glyphicon-search'), 
          name: nil, 
          class: 'btn btn-info',
          title: 'Search' %>
  <% end %>
</div>

app/views/schedule/costume_fittings/_tabs.html.erb
<% klass = ' class="active"'.html_safe %>
<ul class="nav nav-tabs">
  <% if can? :read, resource %>
  	<li<%= klass if params[:controller] == 'schedule/costume_fittings' %>>
      <%= icon_link 'Overview', 'asterisk', schedule_costume_fitting_path(resource) %>
    </li>
  <% end %>
  <% if can? :invitees, resource %>
  	<li<%= klass if params[:controller] == 'schedule/invitees' %>>
      <%= icon_link 'Invitees', 'user', schedule_event_invitees_path(resource.event) %>
    </li>
  <% end %>
</ul>

app/views/schedule/costume_fittings/edit.html.erb
<% provide(:title, 'Edit Costume Fitting') %>
<% provide(:header_current, 'Calendar') %>
<% provide(:sidebar_current, 'Costume Fittings') %>

<% content_for :page_header do %>
  <%= @costume_fitting.title %>
  <small>Edit</small>
<% end %>

<% content_for :tabs do %>
	<%= render 'schedule/costume_fittings/tabs', resource: @costume_fitting %>
<% end %>

<%= simple_form_for @costume_fitting_form, url: schedule_costume_fitting_path(@costume_fitting), method: :put do |f| %>
	<%= show_error_messages @costume_fitting_form %>
  <%= render 'form', :f => f %>

  <%= form_actions do %>
    <%= f.submit 'Update Costume Fitting', class: 'btn btn-primary' %>
    <%= link_to 'Cancel', schedule_costume_fitting_path(@costume_fitting), class: 'btn btn-link' if can? :read, CostumeFitting %>
  <% end %>
<% end %>

app/views/schedule/costume_fittings/index.html.erb
<% provide(:title, 'Costume Fittings') %>
<% provide(:header_current, 'Calendar') %>
<% provide(:sidebar_current, 'Costume Fittings') %>

<div class="page-header">
	 <h1><%= yield(:title) %>
     <div class="pull-right">
       <%= new_button "Add Costume Fitting", new_schedule_costume_fitting_path if can? :create, CostumeFitting %>
     </div>
   </h1>
</div>

<%= render 'schedule/costume_fittings/search_form' %>

<div class="row">
	<table class="table table-striped">
		<thead>
	  	<tr>
	  		<th>Title</th>
	  		<th>Date</th>
        <th>Location</th>
	  		<th class="mash-col-1-btn">&nbsp;</th>
	  	</tr>
	  </thead>
	  <tbody>
	  	<% @costume_fittings.each do |fitting| %>
				<tr>
					<td>
						<% if can? :update, fitting %>
							<%= link_to fitting.title, schedule_costume_fitting_path(fitting), :id => "edit_#{fitting.id}" %>
            <% else %>
              <%= fitting.title %>
						<% end %>
          </td>
          <td><%= fitting.start_date %><br /><%= fitting.time_range %></td>
					<td><%= name_or_tbd(fitting.location) %></td>
					<td class="mash-col-1-btn">
						<%= delete_button nil, schedule_costume_fitting_path(fitting), :class => 'btn-xs', :id => "delete_#{fitting.id}" if can? :destroy, fitting %>
					</td>
				</tr>
			<% end %>
      <% if @costume_fittings.size == 0 %>
        <tr><td colspan="4">None found</td></tr>
      <% end %>
		</tbody>
	</table>
	<%= will_paginate(class: 'pagination', previous_label: "&laquo;", next_label: "&raquo;")%>
</div>

app/views/schedule/costume_fittings/new.html.erb
<% provide(:title, 'Add Costume Fitting') %>
<% provide(:header_current, 'Calendar') %>
<% provide(:sidebar_current, 'Costume Fittings') %>

<div class="page-header">
  <h1>Costume Fittings
    <small>Add</small>
  </h1>
</div>

<div class="row">
  <%= simple_form_for @costume_fitting_form, url: schedule_costume_fittings_path do |f| %>
  	<%= show_error_messages @costume_fitting_form %>
    <%= render 'form', :f => f %>
    
    <%= form_actions do %>
      <%= f.button :submit %>
      <%= link_to 'Cancel', schedule_costume_fittings_path, class: 'btn btn-link' if can? :read, CostumeFitting %>
    <% end %>
  <% end %>
</div>

app/views/schedule/costume_fittings/show.html.erb
<% provide :title, @costume_fitting.title %>
<% provide :header_current, 'Calendar' %>
<% provide :sidebar_current, 'Costume Fittings' %>

<% content_for :page_header do %>
  <%= @costume_fitting.title %>
  <div class="pull-right">
    <%= edit_button 'Edit', edit_schedule_costume_fitting_path(@costume_fitting) if can? :update, @costume_fitting %>
  </div>
<% end %>

<% content_for :tabs do %>
	<%= render 'schedule/costume_fittings/tabs', resource: @costume_fitting %>
<% end %>

<%= render 'schedule/costume_fittings/detail' %>